apiVersion: v1
kind: PersistentVolume
metadata: 
  name: ceph-pv
spec: 
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  rbd: 
    monitors: 
      - 172.23.101.152:6789
    pool: data
    image: data
    user: admin
    secretRef: 
      name: ceph-secret
    fsType: ext4
    readOnly: false
